# Add valid YAML syntax here111
# Example:
    name: PR Check
    on:
        pull_request:
            branches:
                - main

    jobs:
        check:
            runs-on: ubuntu-latest
            steps:
                - name: Say Hello World
                  run: echo "Hello World"
                # - uses: actions/checkout@v4
                #   with:
                #     fetch-depth: 0

                # - name: check version updated
                #   run: |
                #     git diff origin/main..HEAD -- package.json | awk '/+  "version/ {print $3}' | grep -q -v '0.0.0'  || { echo "version not updated in package.json"; exit 1; }